version: 2
updates:

  # Maintain repository dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain module dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain documentation dependencies for npm
  - package-ecosystem: "npm"
    directory: "/documentation"
    schedule:
      interval: "daily"