---
name: Bug Report
description: Something isn't working as expected
labels: 
  - type:bug
body:
- type: checkboxes
  id: search
  attributes:
    label: Please avoid duplicates
    options:
      - label: I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.
        required: true
- type: checkboxes
  id: environment
  attributes:
    label: Related environment(s)
    description: Please select the environment(s) that are relevant to your bug report
    options:
      - label: Project is built using JavaScript
      - label: Project is built using TypeScript
      - label: The problem seems Unity related
      - label: The problem seems React related
      - label: The problem seems module related
      - label: The problem occurs during editor-Time
      - label: The problem occurs during runtime
- type: input
  id: react-unity-webgl-version
  attributes:
    label: React-Unity-WebGL Version
    description: Which version of the Module is installed in your project?
  validations:
    required: true
- type: input
  id: react-version
  attributes:
    label: React Version
    description: Which version of the React are you using?
  validations:
    required: true
- type: input
  id: unity-version
  attributes:
    label: Unity Version
    description: Which version of the Unity did you use to create your build?
  validations:
    required: true
- type: textarea
  id: summary
  attributes:
    label: What happened?
    description: Please share any other relevant information not mentioned above. What did you expect to happen? What do you think the problem might be?
- type: textarea
  id: testcase
  attributes:
    label: Reproducible test case
    description: |
      If possible, please create a minimal test case that reproduces your problem.
  validations:
    required: true
- type: checkboxes
  id: contributor
  attributes:
    label: Would you be interested in contributing a fix?
    options:
      - label: "yes"