name: Publish To NPM
on:
  release:
    types:
      - published
jobs:
  main:
    name: Main
    environment:
      name: Node Package Registry
      url: https://www.npmjs.com/package/react-unity-webgl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1 
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm install
      - name: Compile Source
        run: npm run compile
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}