name: Publish Documentation

on:
  push:
    paths: 
      - documentation/**

jobs:
  main:
    name: Publish Documentation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install and Build Docusaurus
        run: |
          cd documentation
          npm install
          npm run build
        
      # TODO -- Publish /documentation/build