name: Publish To GPR
on:
  release:
    types:
      - published
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1 
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@jeffreylanters'
      - name: Install Dependencies
        run: npm install
      - name: Alter Package For GPR
        run: node .github/actions/alter-package-for-gpr.js
      - name: Compile Source
        run: npm run compile
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}