name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    name: Publish to NPM

    runs-on: ubuntu-latest

    environment:
      name: Node Package Registry
      url: https://npmjs.com/react-unity-webgl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Build JS
        run: npm run compile

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Package build
        run: |
          PACKAGE_FILE_NAME=$(npm pack)
          mv $PACKAGE_FILE_NAME react-unity-webgl.tgz

      - name: Create Release
        uses: ncipollo/release-action@7461bfe83946fc198f507edec4c13f2cda9102dd
        with:
          name: Release ${{ github.ref }}
          body: React Unity WebGL Release ${{ github.ref }}
          artifacts: react-unity-webgl.tgz
          artifactContentType: application/tar
          discussionCategory: Releases
          token: ${{ secrets.GITHUB_TOKEN }}
